import pandas as pd
import scanpy as sc
import os
from matplotlib import pyplot as plt
import seaborn as sns
import matplotlib as mpl
import decipher as dc  # <-- Global import

mpl.rcParams["pdf.fonttype"] = 42
mpl.rcParams["ps.fonttype"] = 42


def plot_embedding_flexible(
    adata,
    latent_space,
    color_key,
    figsize,
    folder,
    file_suffix="",
    title=None,
    show_legend=True,
):
    """
    A flexible plotting function to color embeddings by either
    categorical batch ('dataset_id') or continuous pseudotime ('latent_t').
    """
    fig, ax = plt.subplots(1, 1, figsize=figsize)
    adata.obs["branch_id"] = adata.obs["branch_id"].astype(str)

    # --- Auto-rotate Decipher (COMMENTED OUT) ---
    # This function seems to be missing from your installed version of 'decipher'.
    # It is only for visual alignment, so we can safely skip it.
    # if latent_space == "decipher_decipher_v":
    #     # The 'dc' import is now global, no need to import here
    #     dc.tl.decipher_rotate_space(
    #         adata,
    #         v1_col="latent_t",  # Always rotate based on pseudotime
    #         obsm_key_v="decipher_decipher_v",
    #         auto_flip_decipher_z=False,
    #     )

    # --- Handle Coloring ---
    palette = None
    if color_key == "dataset_id":
        # GOAL A: Color by batch
        adata.obs["dataset_id"] = adata.obs["dataset_id"].astype("category")
        cats = list(adata.obs["dataset_id"].cat.categories)
        palette_map = {"no_shift": "#1f77b4", "shift_0.5": "#d62728"}
        if all(c in palette_map for c in cats):
            palette = [palette_map[c] for c in cats]
            adata.uns["dataset_id_colors"] = palette  # Set uns for scanpy
    
    # For 'latent_t' (GOAL B), scanpy will use the default 'viridis' map.
    
    sc.pl.embedding(
        adata,
        basis=latent_space,
        color=color_key,
        palette=palette,  # Pass the custom palette
        wspace=0.5,
        hspace=0.5,
        ax=ax,
        size=30,
        show=False,
        legend_loc="on data" if (color_key == "dataset_id" and show_legend) else None,
    )

    # --- Clean up plot ---
    if color_key == "latent_t":
        # Adjust continuous colorbar
        axes_list = fig.get_axes()
        if len(axes_list) > 1:
            cbar = axes_list[-1]
            cbar.set_yticks([0, 1])

    sns.despine()
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xlabel("")
    ax.set_ylabel("")

    # --- Set Title ---
    titles = {
        "latent": "Ground truth",
        "X_umap": "UMAP",
        "X_fd": "Force-directed",
        "X_scVI_umap": "scVI UMAP",
        "decipher_decipher_v": "Decipher $v$",
    }
    if title is None:
        title = titles.get(latent_space, latent_space) # Get title from dict, or use key
    ax.set_title(title, fontsize=12, pad=5)

    save_path = f"{folder}/{latent_space}{file_suffix}.pdf"
    plt.savefig(save_path, bbox_inches="tight")
    print(f"   ... saved {save_path}")
    plt.close(fig)  # Close figure to save memory


# ==================================================================
# MAIN EXECUTION BLOCK
# ==================================================================
if __name__ == "__main__":
    
    folder = "figures/paper"
    os.makedirs(folder, exist_ok=True)
    figsize = [2.5, 2] # Small size for individual plots

    # --- 1. Load the main data ---
    # This file has the "no_shift" and "shift_0.5" data
    # It must be generated by running simulations.py first
    try:
        adata = sc.read("figures/adata_density_0.0_seed_4.h5ad")
    except FileNotFoundError:
        print("Error: File 'figures/adata_density_0.0_seed_4.h5ad' not found.")
        print("Please run simulations.py first to generate the data.")
        exit()


    # --- 2. GENERATE BATCH PLOTS (Your new request) ---
    # Plots colored by the simulated batch ('dataset_id')
    print("\n--- Generating plots colored by batch ('dataset_id') ---")
    spaces_to_plot_batch = ["latent", "decipher_decipher_v", "X_umap"]
    
    for space in spaces_to_plot_batch:
        print(f"Plotting {space}...")
        plot_embedding_flexible(
            adata,
            latent_space=space,
            color_key="dataset_id",  # <-- Tell function to use batch
            figsize=figsize,
            folder=folder,
            file_suffix="_batch_colored"
        )

    # --- 3. GENERATE PSEUDOTIME PLOTS (Original Fig 2b style) ---
    # Plots colored by the pseudotime ('latent_t')
    print("\n--- Generating plots colored by pseudotime ('latent_t') ---")
    
    # Let's plot the ones from the paper (Fig 2b)
    spaces_to_plot_pseudo = ["decipher_decipher_v", "X_umap"]

    for space in spaces_to_plot_pseudo:
        print(f"Plotting {space}...")
        plot_embedding_flexible(
            adata,
            latent_space=space,
            color_key="latent_t",  # <-- Tell function to use pseudotime
            figsize=figsize,
            folder=folder,
            file_suffix="_pseudo_colored",
            show_legend=False
        )
    
    # --- 4. GENERATE SIMULATED DENSITY PLOTS (Original Fig 2a) ---
    # The 3-panel ground truth plot showing different densities
    print("\n--- Generating 3-panel density plot (Fig 2a style) ---")
    for density in [0.0, 0.05, 0.1]:
        try:
            adata_density = sc.read(f"figures/adata_density_{density}_seed_4.h5ad")
        except FileNotFoundError:
            print(f"Warning: 'adata_density_{density}_seed_4.h5ad' not found. Skipping.")
            continue
            
        print(f"Plotting latent space for density {density}...")
        plot_embedding_flexible(
            adata_density,
            latent_space="latent",
            color_key="latent_t",  # <-- Color ground truth by pseudotime
            figsize=figsize,
            folder=folder,
            file_suffix=f"_density_{density}",
            title=f"Simulated - density {int(density*100)}%",
            show_legend=False
        )

    print(f"\n--- All plotting complete. Figures saved to {folder} ---")